# Generated by Django 3.1.7 on 2021-06-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonce', '0002_auto_20210615_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonce',
            name='level',
            field=models.CharField(default='Pas Important.', max_length=200),
        ),
        migrations.AlterField(
            model_name='anonce',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
